clouds:
    source:
        type: os
        host: 172.18.172.50
        user: admin
        password: admin
        tenant: admin
        ephemeral_drives:
          ceph: yes
          convert_diff_file: qcow2
          convert_ephemeral_drive: qcow2
        cinder:
          backend: ceph
          disk_format: qcow2
        temp: /root/temp
        identity:
          connection: mysql+mysqlconnector
    destination:
        type: os
        host: 172.18.172.20
        user: admin
        password: admin
        tenant: admin
        temp: /root/merge
        mysql:
          user: root
          password:
        cinder:
          backend: ceph
        glance:
          convert_to_raw: yes
        ephemeral_drives:
          ceph: no
        transfer_ephemeral:
          compressionion: gzip
          level_compressionion: 9
        transfer_file:
          compressionion: dd
          level_compression: 9
        import_rules:
            default: {}
            overwrite:
                key: {name: control}
                networks:
                 - name: "net04"
        speed_limit: 10MB
        identity:
          connection: mysql+mysqlconnector
key_filename:
    name: privkey
instances:
 - key_name: control
