version: 1
disable_existing_loggers: False
formatters:
  simple:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  info_colored:
    (): colorlog.ColoredFormatter
    format: '%(log_color)s%(levelname)-8s%(reset)s %(current_task)s %(asctime)s %(message)s'
    datefmt: '%m-%d %H:%M:%S'
    log_colors:
      DEBUG: green
      INFO: cyan
      WARNING: yellow
      ERROR: red
      CRITICAL: purple
  debug_colored:
    (): colorlog.ColoredFormatter
    format: '%(log_color)s%(levelname)-8s%(reset)s %(current_task)s [%(name)s; %(pathname)s:%(lineno)s] %(asctime)s %(message)s'
    datefmt: '%m-%d %H:%M:%S'
    log_colors:
      DEBUG: green
      INFO: cyan
      WARNING: yellow
      ERROR: red
      CRITICAL: purple
  console_colored:
    (): colorlog.ColoredFormatter
    format: '%(log_color)s%(levelname)-8s%(reset)s %(current_task)s [%(pathname)s:%(lineno)s] %(asctime)s %(message)s'
    datefmt: '%m-%d %H:%M:%S'
    log_colors:
      DEBUG: green
      INFO: cyan
      WARNING: yellow
      ERROR: red
      CRITICAL: purple
filters:
  show_current_task:
    (): cloudferrylib.utils.log.CurrentTaskFilter
    name_format: '%(name)s'

handlers:
  console:
    class: logging.StreamHandler
    formatter: console_colored
    stream: ext://sys.stdout
    filters: [show_current_task]
    level: INFO
  debug:
    backupCount: 20
    class: cloudferrylib.utils.log.RunRotatingFileHandler
    encoding: utf-8
    filename: 'debug-%(scenario)s-%(date)s.log'
    date_format: '%F-%H-%M-%S'
    formatter: debug_colored
    level: NOTSET
    maxBytes: 100M
    filters: [show_current_task]
  info:
    backupCount: 20
    class: cloudferrylib.utils.log.RunRotatingFileHandler
    encoding: utf-8
    filename: 'info-%(scenario)s-%(date)s.log'
    date_format: '%F-%H-%M-%S'
    formatter: info_colored
    level: INFO
    maxBytes: 100M
    filters: [show_current_task]
loggers:
  cloudferrylib:
    level: DEBUG
    handlers: [console, info]

root:
  level: NOTSET
  handlers: [debug]
